apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: jenkins-agent
    image: shreyasing27/jenkins-agent:latest  # use your DockerHub image name
    ports:
    - containerPort: 22
